### ISSUE TITLE
mdBook is necessary but not a dependency?

### ISSUE THREAD

**Issue by WouterWeynants** [PsichiX/unreal-doc#2]
I got everything working on my desktop earlier, love this documentation toolset.

Installed it on my laptop today, ran `cargo install unreal-doc` expecting it to work like a charm but found out my laptop didn't have mdBook yet and it was not installed with this. Is that intentional for some reason I do not know?

**Comment by PsichiX** [comment]
Oh yes, mdbook is just an optional baking backend and has to be installed independently. I hope I wrote that in Readme, if not I will add this note definitely.

**Comment by WouterWeynants** [comment]
Ah ok, I misunderstood this docs tool to be solely based upon mdbook. Good to know that's just one way of using it! I might experiment with other frontends now...
