### ISSUE TITLE
Add BOM to a file and the table will not parse the document title correctly

### ISSUE THREAD

**Issue by WouterWeynants** [PsichiX/unreal-doc#3]
![image](https://github.com/PsichiX/unreal-doc/assets/15678638/6375eebc-5a6c-4c48-b3b8-966fc7ad630d)

**Comment by WouterWeynants** [comment]
My laptop still had BOM enabled by default in Rider, whereas my desktop had BOM disabled so I'm only spotting this issue now

**Comment by PsichiX** [comment]
Oh,I just added BOM detection to cpp header files parser, I would need to add it to every file loaded into memory.i can fix that on Monday.

**Comment by PsichiX** [comment]
finally got back to pc, fixing the issue

**Comment by PsichiX** [comment]
fixed in version 1.0.8:
https://github.com/PsichiX/unreal-doc/releases/tag/1.0.8
